# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsCli < Formula
  desc ""
  homepage "https://github.com/linzeyan/homebrew-tools"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/linzeyan/ops-cli/releases/download/v0.1.2/ops-cli_v0.1.2_darwin_amd64.tar.gz"
      sha256 "e4dac518d68238ad8475b7145ee7d2fd652ccbdef01c7ec16f74a5280a387ffc"

      def install
        bin.install "ops-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/linzeyan/ops-cli/releases/download/v0.1.2/ops-cli_v0.1.2_darwin_arm64.tar.gz"
      sha256 "fd466e10048ebd819e42c53686fdff27203c82d4054596fd0313dee77df6d07a"

      def install
        bin.install "ops-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linzeyan/ops-cli/releases/download/v0.1.2/ops-cli_v0.1.2_linux_arm64.tar.gz"
      sha256 "52532c4df9de1610350a5b84bf2b0f48c7433121eb133c7d8f707fead4311b9e"

      def install
        bin.install "ops-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linzeyan/ops-cli/releases/download/v0.1.2/ops-cli_v0.1.2_linux_amd64.tar.gz"
      sha256 "320b46f084025f6c47036ad057b078236b582a6e0cfbdbb55d3e89cbca7fa7f1"

      def install
        bin.install "ops-cli"
      end
    end
  end
end
