# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsCli < Formula
  desc ""
  homepage "https://github.com/linzeyan/homebrew-tools"
  version "0.8.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/linzeyan/ops-cli/releases/download/v0.8.4/ops-cli_v0.8.4_darwin_amd64.tar.gz"
      sha256 "8267a94713e40a7c77602ed31da9510fdb98247beb13643ed15a83f622281473"

      def install
        bin.install "ops-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/linzeyan/ops-cli/releases/download/v0.8.4/ops-cli_v0.8.4_darwin_arm64.tar.gz"
      sha256 "3978fc41ac0aea66a989be928fc8d6521b65e7879fda0de8e429a6b0af1ee689"

      def install
        bin.install "ops-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linzeyan/ops-cli/releases/download/v0.8.4/ops-cli_v0.8.4_linux_arm64.tar.gz"
      sha256 "0d26dd3ce1293380b42ee5770c1a018423d1db6e17ac88bbf6fd1b2928180856"

      def install
        bin.install "ops-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linzeyan/ops-cli/releases/download/v0.8.4/ops-cli_v0.8.4_linux_amd64.tar.gz"
      sha256 "c78f6eda70a699268c59bc60c681bf69d00a16f825ad6cdc9deb23921fd8856b"

      def install
        bin.install "ops-cli"
      end
    end
  end
end
